version: "2"
services:
    service_nginx:
        build: ./server/nginx
        depends_on:
            - service_1
            - service_2
            - service_3
        ports:
            - "8080:80"
    service_1:
        build: ./server
        ports:
            - "8008"
        depends_on:
            # - redis-primary
            # - redis-secondary
            - redis
    service_2:
        build: ./server
        ports:
            - "8008"
        depends_on:
            # - redis-primary
            # - redis-secondary
            - redis
    service_3:
        build: ./server
        ports:
            - "8008"
        depends_on:
            # - redis-primary
            # - redis-secondary
            - redis
    client_nginx:
        build: ./client/nginx
        depends_on:
            - client_1
            - client_2
        ports:
            - "3000:80"
    client_1:
        build: ./client
        ports:
            - "3000"
    client_2:
        build: ./client
        ports:
            - "3000"
    redis:
        image: redis
        ports:
            - "6379"
    # redis-primary:
    #     image: "bitnami/redis:latest"
    #     ports:
    #         - "6379"
    #     environment:
    #         - REDIS_REPLICATION_MODE=master
    #         - REDIS_PASSWORD=my_password
    # redis-secondary:
    #     image: "bitnami/redis:latest"
    #     ports:
    #         - "6379"
    #     depends_on:
    #         - redis-primary
    #     environment:
    #         - REDIS_REPLICATION_MODE=slave
    #         - REDIS_MASTER_HOST=redis-primary
    #         - REDIS_MASTER_PORT=6379
    #         - REDIS_MASTER_PASSWORD=my_password
    #         - REDIS_PASSWORD=my_password