service_nginx:
    build: ./server/nginx
    links:
        - service_1:service_1
        - service_2:service_2
        - service_3:service_3
    ports:
        - "8080:80"
service_1:
    build: ./server
    ports:
        - "8008"
service_2:
    build: ./server
    ports:
        - "8008"
service_3:
    build: ./server
    ports:
        - "8008"
client_nginx:
    build: ./client/nginx
    links:
        - client_1:client_1
        - client_2:client_2
    ports:
        - "3000:80"
client_1:
    build: ./client
    ports:
        - "3000"
client_2:
    build: ./client
    ports:
        - "3000"
